# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------



include(../common_config.pri)

TEMPLATE = lib

DESTDIR = ../../../bin
DEFINES += SURV_LIBS_BUILD
CONFIG += dll

win32:CONFIG(release, debug|release){
    TARGET = avic.utils
}
else:win32:CONFIG(debug, debug|release){
    TARGET = avic.utils_d
}

include(avic.utils.pri)
