# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.

INCLUDEPATH += ../include

HEADERS += \
    ./Common/SURVIDCreator.h \
    ./UiUtils/CommonDialog.h \
    ./UiUtils/MessageBox.h \
    ./Common/SURVSphericalGeodesyModel.h \
    ./Common/SurvUserConfig.h \
    ./Common/SurvUserPreference.h \
    ./Common/ui_Degree.h \
    ./UiUtils/ConfirmDialog.h \
    ./UiUtils/DSCheckComboBox.h \
    ./UiUtils/DSCheckComboModel.h \
    ./DBEngine/DataBaseUtil.h \
    ./Common/DegreeUtil.h \
    ./UiUtils/InformationDialog.h \
    ./UiUtils/LabelDelegate.h \
    ./GISMap/MainMap2DSignalMgr.h \
    ./Common/SURVAppConfig.h \
    ./Common/SURVDataExchanger.h \
    ./UiUtils/SelColorLabel.h \
    ./Common/SurvLatLonCtrl.h \
    ./UiUtils/CustomTabWidget.h \
    ./UiUtils/TextEditDelegate.h

SOURCES += \
    ./UiUtils/ConfirmDialog.cpp \
    ./UiUtils/CommonDialog.cpp \
    ./UiUtils/MessageBox.cpp \
    ./UiUtils/DSCheckComboBox.cpp \
    ./UiUtils/DSCheckComboModel.cpp \
    ./DBEngine/DataBaseUtil.cpp \
    ./Common/DegreeUtil.cpp \
    ./UiUtils/InformationDialog.cpp \
    ./UiUtils/LabelDelegate.cpp \
    ./GISMap/MainMap2DSignalMgr.cpp \
    ./Common/SURVAppConfig.cpp \
    ./Common/SURVDataExchanger.cpp \
    ./Common/SURVIDCreator.cpp \
    ./Common/SURVSphericalGeodesyModel.cpp \
    ./UiUtils/SelColorLabel.cpp \
    ./Common/SurvLatLonCtrl.cpp \
    ./Common/SurvUserConfig.cpp \
    ./Common/SurvUserPreference.cpp \
    ./UiUtils/TextEditDelegate.cpp \
    ./UiUtils/CustomTabWidget.cpp

FORMS += \
    ./UiUtils/ConfirmDialog.ui \
    ./UiUtils/InformationDialog.ui

RESOURCES += Resource.qrc
